增加“投稿设置”配置描述
chr233/XinjingdailyBot pull request #6
Opened 2023-02-18 16:26 UTC by ShadowsSide

2023-02-18 17:24 UTC, chr233 requested changes
你貌似传了个无关文件上来

2023-02-18 17:25 UTC, merged

2023-02-18 17:25 UTC, chr233 commented
另外 PureWords 不是 bool 类型，是 string 类型

2023-02-19 06:03 UTC, ShadowsSide commented
抱歉，这个当时添加用来触发 Action 的文件，忘记删除了。

PureWords 的话，如果要更改还是要到这个位置修改吧？所以我开关这边写了bool  😂

[    <value>🏳️‍⚧️|🇺🇦|🇹🇼|🍥|🏳‍⚧</value>](https://github.com/chr233/XinjingdailyBot/blob/f8209d1aeed59e0b53be5c2df86f2316280572ab/XinjingdailyBot.Infrastructure/Localization/Emojis.resx#L139)

2023-02-19 08:34 UTC, chr233 commented
触发action打个tag就行了

2023-02-19 08:34 UTC, chr233 commented
> 抱歉，这个当时添加用来触发 Action 的文件，忘记删除了。
> 
> PureWords 的话，如果要更改还是要到这个位置修改吧？所以我开关这边写了bool  😂
> 
> [    <value>🏳️‍⚧️|🇺🇦|🇹🇼|🍥|🏳‍⚧</value>](https://github.com/chr233/XinjingdailyBot/blob/f8209d1aeed59e0b53be5c2df86f2316280572ab/XinjingdailyBot.Infrastructure/Localization/Emojis.resx#L139)

不需要这个功能就把字段设成""就行了

2023-02-19 15:46 UTC, ShadowsSide commented
> > 抱歉，这个当时添加用来触发 Action 的文件，忘记删除了。
> > PureWords 的话，如果要更改还是要到这个位置修改吧？所以我开关这边写了bool  😂
> > [    🏳️‍⚧️|🇺🇦|🇹🇼|🍥|🏳‍⚧](https://github.com/chr233/XinjingdailyBot/blob/f8209d1aeed59e0b53be5c2df86f2316280572ab/XinjingdailyBot.Infrastructure/Localization/Emojis.resx#L139)
> 
> 不需要这个功能就把字段设成""就行了

好的，我看到这段还以为只是个开关，原来 keyword 也可以直接加在这里是吧。

https://github.com/chr233/XinjingdailyBot/blob/3482ac382a485b91e41988c236fa041761a4116f/XinjingdailyBot.WebAPI/appsettings.json#L60